version: '3.2'
services:
  graphdb:
    image: nabda/graphdb:8.9.0-free
    container_name: graphdb
    volumes:
      - ./data/graphdb/data:/opt/graphdb/home/data
      - ./data/graphdb/work:/opt/graphdb/home/work
    ports:
      - 7200:7200
  neo4j:
    image: neo4j
    container_name: neo4j
    volumes:
      - ./data/neo4j/data:/data
      - ./data/neo4j/plugins:/plugins
      - ./data/neo4j/conf/neo4j.conf:/conf/neo4j.conf
    environment:
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
    ports:
      - 7474:7474
      - 7687:7687
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - target: 9094
        published: 9094
        protocol: tcp
        mode: host
    environment:
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
